export const rank = {
  Ace: 'ace',
  Two: 'two',
  Three: 'three',
  Four: 'four',
  Five: 'five',
  Six: 'six',
  Seven: 'seven',
  Eight: 'eight',
  Nine: 'nine',
  Ten: 'ten',
  Jack: 'jack',
  Queen: 'queen',
  King: 'king',
};
